DROP TABLE Ingredient CASCADE CONSTRAINTS;
DROP TABLE Meal CASCADE CONSTRAINTS;
DROP TABLE IsInMeal CASCADE CONSTRAINTS;
DROP TABLE Menu CASCADE CONSTRAINTS;
DROP TABLE IsOnMenu CASCADE CONSTRAINTS;
DROP TABLE Chef CASCADE CONSTRAINTS;
